name: Adicionar label bugfix no pr

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  add-bugfix-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checar se o pr referencia uma issue
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || "";
            const prTitle = context.payload.pull_request.title || "";

            const issueReferencePattern = /(fixe?[sd]?|close[sd]?|resolve[sd]?)\s+#\d+/i;

            if (issueReferencePattern.test(prBody) || issueReferencePattern.test(prTitle)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['bugfix']
              });
              core.info("Label 'bugfix' added to the PR.");
            } else {
              core.info("No issue reference found. Label not added.");
            }
