name: "Label Pull Requests"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: false
          dot: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
